---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - api.worker-deployment
  resources:
  - workerdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.worker-deployment
  resources:
  - workerdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - api.worker-deployment
  resources:
  - workerdeployments/status
  verbs:
  - get
  - patch
  - update
