# permissions for end users to edit workerdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: workerdeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: workerdeployment
    app.kubernetes.io/part-of: workerdeployment
    app.kubernetes.io/managed-by: kustomize
  name: workerdeployment-editor-role
rules:
- apiGroups:
  - api.worker-deployment
  resources:
  - workerdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.worker-deployment
  resources:
  - workerdeployments/status
  verbs:
  - get
